name: skillstack
description: A micro-skill tracking application to master your abilities.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core & State Management
  flutter_riverpod: ^2.4.9
  go_router: ^12.1.3
  shared_preferences: ^2.2.2

  # Database
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1

  # Utilities
  permission_handler: ^11.1.0
  flutter_local_notifications: ^16.3.0
  image_picker: ^1.0.4
  intl: ^0.18.1 # For date/time formatting

  # UI & Animations
  dynamic_color: ^1.6.8
  flutter_animate: ^4.3.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  # Define assets for pre-built themes and app icon
  assets:
    - assets/images/
    - assets/icons/
